### ISSUE TITLE
Add name tags along streams and rivers 

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#115]
Perhaps by splitting them and adding short unnamed stream sections to the data before rendering.

**Comment by zstadler** [comment]
This suggestion is hard to adapt for different zoom levels and different stream lengths.

**Comment by yrtimiD** [comment]
On IHM hiking, zoom 15, streams have name tags like once for each 40 km, while on Standard layer on official OSM each 1 km. It's the same issue as discussed here?

**Comment by zstadler** [comment]
> On IHM hiking, zoom 15, streams have name tags like once for each 40 km, while on Standard layer on official OSM each 1 km. It's the same issue as discussed here?

Basically, yes.

Maperitive, the map rendering software used here, is capable of putting only a single label on a line. Moreover, it merges different connected ways with compatible tags into a single line. As a result, there could be a single label on a 1000km long river.

This issue is a placeholder for finding ways to overcome this limitation. The author of Maperitive could not help on this, unfortunately.

**Comment by zstadler** [comment]
Addressed as part of #93
