### ISSUE TITLE
BIke map label collision

### ISSUE THREAD

**Issue by SafwatHalaby** [IsraelHikingMap/Map#180]
An image is worth a thousand ~~words~~ labels

![1](https://user-images.githubusercontent.com/5030488/32408832-46f69d9a-c1a8-11e7-8c2b-3cda217a34c1.png)

Place: https://israelhiking.osm.org.il/#!/17/32.6933/35.0463

**Comment by HarelM** [comment]
This is defined as "label collision" and it is a limitation of our time generation software.

**Comment by zstadler** [comment]
On the other hand, this was not intended for urban areas and was solved for select cities.
Perhaps @valleyofdawn should be looking at it.

**Comment by valleyofdawn** [comment]
I'll add Dalia to the list of treated cities.

**Comment by valleyofdawn** [comment]
Perhaps we should add all place=city to the list instead of select locations? What do you think?

**Comment by zstadler** [comment]
Is there any progress on this? I would like to close this issue.

**Comment by SafwatHalaby** [comment]
Reference: https://github.com/IsraelHikingMap/Map/pull/199

**Comment by valleyofdawn** [comment]
Not working in half the cities because the relation does not have a place name.

Name | Urban density reduction | Problem
-- | -- | --
Acre | Wrong | Relation with no place   Polygon with place
Afula | Wrong | Relation with no place   Polygon with place   Node with place
Ashdod | Right |  
Ashkelon | Wrong | Relation with no place   Polygon with place
Bat Yam | Right |  
Be'er Sheva |   |  
Bnei Brak | Right |  
Carmiel | Wrong | Relation with no place   Polygon with place
Daliyat al-Karmel | Wrong | Relation with no place
Eilat | Wrong | Relation with no place   Polygon with place
Givatyim | Right |  
Hadera | Wrong | Relation with no place   Polygon with place
Haifa | Right |  
Herzliya | Right |  
Holon | Right |  
Jerusalem | Right |  
Kfar Sava | Right |  
Lod | Wrong | Not Included
Modiin-Maccabim-Reut | Wrong | Relation with no place   Landuse polygon with place
Nahariyya | Wrong | Relation with no place   Polygon with place
Nazareth | Wrong | Relation with no place   Polygon with place
Nazerat Illit | Wrong | Not Included
Nes Ziona | Right |  
Netanya | Right |  
Petah Tikva | Right |  
Raanana | Right |  
Ramat Gan | Right |  
Ramat HaSharon | Right |  
Ramla | Wrong | Not Included
Rehovot | Right |  
Rishon LeZion | Right |  
Safed | Wrong | Relation with no place   Polygon with place   Node with place
Tel Aviv-Yafo | Right |  
Zichron Yaakov | Wrong | Not Included

**Comment by valleyofdawn** [comment]
Name | Current condition | Way | Relation | Node | Included in list
-- | -- | -- | -- | -- | --
Acre | Wrong | Residential |   | yes | Yes
Afula | Wrong | Residential |   | yes | Yes
Ashdod | Right | Residential | Municipal | yes | Yes
Ashkelon | Wrong | Residential |   | yes | Yes
Bat Yam | Right |   | Municipal | yes | Yes
Be'er Sheva | Wrong | Residential |   | yes | Yes
Beer Sheva | Wrong |   |   | yes | No
Bnei Brak | Right |   | Municipal | yes | Yes
Carmiel | Wrong | Residential |   |   | Yes
Daliyat al-Karmel | Wrong |   |   | yes | Yes
Eilat | Wrong |   |   | yes | Yes
Givatyim | Right |   |   |   | Yes
Givatayim | Right |   | Residential | yes | No
Hadera | Wrong | Residential |   | yes | Yes
Haifa | Right |   | Municipal | yes | Yes
Herzliya | Right | Residential | Municipal | yes | Yes
Holon | Right | Residential | Municipal | yes | Yes
Jerusalem | Right |   | Residential | yes | Yes
Kfar Sava | Right |   | Municipal |   | Yes
Kfar Saba |   | Residential |   | yes | No
Lod | Wrong | Residential |   | yes | No
Modiin-Maccabim-Reut | Wrong | Residential |   | yes | Yes
Nahariyya | Wrong |   |   | yes | Yes
Nazareth | Wrong | Residential |   | yes | Yes
Nazerat Illit | Wrong | Residential |   | yes | No
Nes Ziona | Right |   | Municipal |   | Yes
Netanya | Right |   | Residential | yes | Yes
Petah Tikva | Right | Residential | Municipal | yes | Yes
Raanana | Right |   | Municipal | yes | Yes
Ramat Gan | Right |   | Municipal | yes | Yes
Ramat HaSharon | Right |   | Residential | yes | Yes
Ramla | Wrong | Residential |   |   | no
Rehovot | Right | Residential | Municipal | yes | Yes
Rishon LeZion | Right |   | Municipal | yes | Yes
Safed | Wrong |   |   | yes | Yes
Tel Aviv-Yafo | Right |   | Municipal | Yes |  
Zichron Ya'akov | Wrong |   | Residential | Yes | Yes

**Comment by valleyofdawn** [comment]
This is showing only entities with the place tag.
More often than not the relation represents the municipal area and the way shows the residential area. Some cities have both, some one of them and some only a node.
I suggest you add some code, with a separate name list, to the script that deals with ways tagged with place (on top,  not instead of relations).
I'll then populate the lists with the appropriate names (addressing corrections, omissions and aiming for residential areas when possible).

**Comment by valleyofdawn** [comment]
I'll also tag the residential areas of towns with a node only with place=town
