### ISSUE TITLE
Road looks like golany trail

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#187]
## Context - ההקשר
A tertiary road with green colour looks like golany trail.
I know we currently do not mark this trail but this made me think we started to.

## Expected Behavior - ההתנהגות הצפויה
Not sure.

## Actual Behavior - ההתנהגות בפועל
Made me think we are rendering Golany trail.

## Proposed Cause or Fix - סיבה או תיקון מוצעים
Not sure...

## Steps to Reproduce - הוראות לשיחזור הבעיה
Go to:
https://israelhiking.osm.org.il/#!/17/31.6617/34.9367
![image](https://user-images.githubusercontent.com/3269297/34071763-34609c88-e284-11e7-82c3-12b47f7195b3.png)

## Impact - השפעה
Probably low as I'm guessing there aren't many tertiary road with green colour on them.

**Comment by zstadler** [comment]
Although it looks like Golani trail, this is pure coincidence. This is expected given this is just a combination of two colors.

Moreover, this representation is incompatible with the way the map shows national and regional trails - as dash combinations on the side of the trail. If we were showing the Golani Trail on the map, it would look like the Golan Trail below, but with yellow instead of blue.

![image](https://user-images.githubusercontent.com/1304610/34405097-01b65df6-ebba-11e7-9e34-9e72e6d9d546.png)

**Comment by HarelM** [comment]
Yes, you are right.
My only question is if we want to make the green line (or any other trail mark) more subtle on "main" roads (green,red,blue,brown).

**Comment by zstadler** [comment]
Then there will be a question about the meaning of the two shades of green
