### ISSUE TITLE
Quarries are hard to see.

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#21]
These are areas you want to avoid. Currently very subtle light grey.
I like the way Thunderforest Outdoors renders them.

**Comment by HarelM** [comment]
Can you send a screen shot/share link?

**Comment by valleyofdawn** [comment]
Of Thunderforest Outdoors or IHM?

**Comment by valleyofdawn** [comment]
Sorry, turns out it was Landscape, not Outdoors
<iframe src='http://osm.org.il/Israel%20Hiking/IsraelHikingMap.html#/15/32.4800/35.0597?baselayer=http:%2F%2Fa.tile.thunderforest.com%2Flandscape%2F%7Bz%7D%2F%7Bx%7D%2F%7By%7D.png&markers=&Route_1=' width='640' height='390' frameborder='0' scrolling='no' />

**Comment by zstadler** [comment]
It seems to me that the main difference is the contour around the quarry rather than the contrast between the standard background color and the quarry background in each map. Generally, IHM uses lighter colors.

Outdoor's rendering is, in my opinion, is misleading as it draws a cliff around the entire quarry. Moreover, the bottom direction should be inward rather than outward.

The solution, I think, is to add a contour like a fence to show the access restriction to the quarry. 

If anyone adds a cliff to the map, it will also be rendered.
2. Rnder a cliff

**Comment by HarelM** [comment]
+1 fence.

**Comment by zstadler** [comment]
The (Zin quarries)[http://osm.org.il/IsraelHiking/#/14/30.8662/35.1097?baselayer=Israel_Hiking_Map&markers=&Route_1=] show with a lot of fences, that I'm not sure exist...
Perhaps a different rendering of the perimeter would be better.

**Comment by zstadler** [comment]
Not all quarries have fences, especially in the Negev.
Should replace with (something like) Mapnik's new style:
 ![](http://wiki.openstreetmap.org/w/images/4/4e/Rendering-landuse-quarry-mapnik.png)
http://wiki.openstreetmap.org/w/images/4/4e/Rendering-landuse-quarry-mapnik.png

Also, replace the rendering of the border with something else.

**Comment by zstadler** [comment]
https://github.com/gravitystorm/openstreetmap-carto/raw/master/symbols/quarry.png
and
https://commons.wikimedia.org/wiki/File:Schlaegel_und_Eisen_nach_DIN_21800.svg
seems to be alternative sources for the icon

**Comment by HarelM** [comment]
Nice!
