### ISSUE TITLE
Meadow rendering

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#22]
Meadows in Israel look more like scrub than like farmland. The current texture might be misleading.

**Comment by zstadler** [comment]
This is intentional, according to the meaning of the tags.

A [meadow]() is "area of land primarily vegetated by grass plus other non-woody plants" while [scrub](http://wiki.openstreetmap.org/wiki/Tag:natural%3Dscrub) is "dominated by shrubs (bush), often also including grasses, herbs, and geophytes."

Both tags refer to natural, non agriculture areas unless meadow=agricultural is used (no occurrence in Israel yet).
