### ISSUE TITLE
Double render of track and bike route?

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#23]
Check this out:
http://osm.org.il/IsraelHiking/#/16/32.8962/35.6186?baselayer=Israel_Hiking_Map&markers=&Route_1=
Looks like two lines are rendered instead of one.
This looks OK when trying to edit, not sure if the map is just not up to date...?

**Comment by zstadler** [comment]
Until recently there were several sections of the kinneret perimeter cycle route (צופה כנרת) with a mapping error where there was an overlap of a cycleway and a track/footway/etc instead of including the track/footway/etc  as part of a regional cycle route relation. Seem like the mapping issue is now fixed.

If still see an issue, please put a marker on the applicable track.
