### ISSUE TITLE
שגיאה בהוספת תמונות - סיבוב תמונה

### ISSUE THREAD

**Issue by Amirstad** [IsraelHikingMap/Map#238]
## Context - ההקשר
הוספת תמונה לנקודת ציון קיימת

![WhatsApp Image 2019-04-14 at 11 11 47](https://user-images.githubusercontent.com/32457970/56090855-57b14080-5eb0-11e9-8cf6-5ad5e8667a7a.jpeg)

## Expected Behavior - ההתנהגות הצפויה
הוספת תמונה שצולמה אנכית דרך האפליקציה והופעתה לאחר סיבוב

## Actual Behavior - ההתנהגות בפועל
התמונה נוספה על הצד על אף שצולמה אנכית, לא קיימת אפשרות להורות על סיבוב

## Proposed Cause or Fix - סיבה או תיקון מוצעים
הוספת כפתור סיבוב תמונה, ובחינת הסיבה שבגינה התמונה אינה מופיעה ישר מלכתחילה.

## Steps to Reproduce - הוראות לשיחזור הבעיה
1. כניסה לנקודת עניין קיימת
2. כניסה למסך עריכה
3. הוספת תמונה מגלריה
4. בחירת תמונה שצולמה באופן אנכי
5. Voila!

## Impact - השפעה
קושי בהעלאת תמונות ועדכון נקודות עניין

## Your Environment - סביבת העבודה שלך
* Operating System and version - מערכת ההפעלה וגרסתה:    אנדרואיד 8.0.0

* Web Browser and version - דפדפן וגרסתו:    
אפליקציה

**Comment by HarelM** [comment]
Thanks for reporting this issue.
We are aware of it, but currently lack the resources to fix it.
You can follow this issue here:

**Comment by HarelM** [comment]
Thanks for reporting this issue.
We are aware of it, but currently lack the resources to fix it...
You can follow this issue here:
https://github.com/IsraelHikingMap/Site/issues/932
Closing this as duplicate.

**Comment by HarelM** [comment]
@Amirstad currently, until this issue is resolved you can download the image from you device to a desktop computer and upload the image from the desktop (I know it's a shitty workaround...).
You can also upload a new version of the image if you can find it here:
https://commons.wikimedia.org/wiki/Category:Israel_Hiking_Map
You'll need a wikimedia account for this though...
