### ISSUE TITLE
Footway that can be used by bikes should be rendered like paths?

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#26]
So, we have routing but it looks weird now since the bike routing can go through footway (.....) if it doesn't have a bicycle=no tag (which is possible according to OSM footway wiki).
Should we render footway (......) only for highway=footway AND bicycle=no?

**Comment by zstadler** [comment]
Bike routes should not go through footways, much like hikers are forbidden from cycleways.
The highway=path tag is used for trails suitable for both hikers and bikers.

Note that some paths have bicycle=designated tag, and we render then just like cycleways. However, routing for hikers can go through them.

**Comment by HarelM** [comment]
I looked here: http://wiki.openstreetmap.org/wiki/Tag:highway%3Dfootway but it doesn't say bikers can't use footway...  :-(

**Comment by zstadler** [comment]
It does say "For multi-use or unspecified paths and trails used by a
variety of non-motorised traffic the tag highway
<http://wiki.openstreetmap.org/wiki/Key:highway>=path
<http://wiki.openstreetmap.org/wiki/Tag:highway%3Dpath> may be better
suited."
I's a polite way of saying that "path" should be used instead of footway if
bicycles are expected to share the road.
