### ISSUE TITLE
Update legend with latest changes.

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#36]
For example water hole.
Make sure to show text for place of worship since they do not get written today.

**Comment by zstadler** [comment]
I'm planning to adopt the legend style of the [MTB map](http://israelhiking.osm.org.il/content/images/legend_mtb.png).
It is clear, simple, and the uniform text style is independent of the text styles on the map.

**Comment by zstadler** [comment]
Potentially use [globalmaptiles.py](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/globalmaptiles.py) from [MapTiler](http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/) to create the OSM file for the Legend programmatically.

Define 
* Location (lat/lon) of top-left corner
* Dimensions (in pixels or Km) for:
  * Width of each column, text, way, and areas
  * Height of each entry in the legend and areas

Each entry will be created by a function/method call, such as
* Header
* Sub-header
* Way entry
* Icon entry
* Area entry
* Way with nodes, such as power line with poles
* Start a new column

Fonts and font sizes are determined in the rules definition.

**Comment by HarelM** [comment]
How will one manage two icons for the same POI?
How will one add a POI that is not a way or an area?
I think that globalmaptiles.py script is a bit of an overkill for what we need - just use a constant values for new column/rows spacing/padding...
Other the the two questions above I think the interface is pretty self explanatory.

**Comment by zstadler** [comment]
> How will one manage two icons for the same POI?
How will one add a POI that is not a way or an area?

I'm not sure what you mean by "two icons for the same POI". If two different icons exist in the map, each of them will be a separate entry in the legend with its own different description.

The legend has 3 types of entries, and each of them can be added to the OSM file.

> I think that globalmaptiles.py script is a bit of an overkill for what we need - just use a constant values for new column/rows spacing/padding...

Because of the Mercator projection, using constant lat/lon spaces will create a distorted, non rectangular shape. If you look at the current osm file of the legend, you will notice that the latitude and longitude are not preserved when going east-west or north-south between legend items.
Perhaps this issue could be minimized by placing the legend near the equator...

globalmaptiles.py also provides us with an easy way to define the dimensions in pixels.

**Comment by HarelM** [comment]
More than one icon for the same POI label - what I had in mind is the 3 types of gates, I think putting three icons there and one label is better than placing a label for every type of gate, while this might be the only currently item that does that it might be something we'll want in the future and also the MTB has the same for issue peaks, I think.
> Because of the Mercator projection, using constant lat/lon spaces will create a distorted, non rectangular shape.

Your call...

**Comment by zstadler** [comment]
I think that if we bothered to give different gates different icons, each
of them can get an entry of its own.

See, for example, the three types of cabins in the Norwegian MTB legend.

**Comment by HarelM** [comment]
OK, I don't feel that strongly about it :-)

**Comment by zstadler** [comment]
Also, add legend for the different tracktype values

**Comment by zstadler** [comment]
![cemetery](https://cloud.githubusercontent.com/assets/1304610/14898238/791fb024-0d8e-11e6-9518-e459490c7adb.png)

**Comment by HarelM** [comment]
See:
https://github.com/IsraelHikingMap/Site/issues/234
Legend is maintained in the site project now.
