### ISSUE TITLE
Add Ladder Icon to let the user know a trail consists of ladders

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#62]
Relevant to ```ladder=yes``` POI.
Remember to update the legend too.

**Comment by valleyofdawn** [comment]
Laddet icon now available at mtb folder. Optimized for 17px

**Comment by zstadler** [comment]
Currently, there are no ladders mapped in Israel.
See http://overpass-turbo.eu/s/jA4

**Comment by HarelM** [comment]
I don't see a commit, does this mean you didn't add it? Because I think we should map it for future usage.

**Comment by zstadler** [comment]
This enhancement was opened 6 months ago. In the meantime, no ladders have been mapped. 

I've closed the request because it is currently irrelevant. 

Please reopen the request when there is a significant mapping of ladders in Israel. The above Overpass query can be used to assess the progress of ladder mapping.

**Comment by HarelM** [comment]
I would love to add them, but since I usually take my dogs with me when hiking I tend not to do hikes that have ladders, so this is kinda catch 22...
I was hoping that it will be mapped so I'd know which hikes I can't do.
But maybe this is not so realistic, I'll continue trying to find this data from the sites that list the trails... :-(

**Comment by zstadler** [comment]
It looks like rope mappings are also needed for such trip planning...

**Comment by HarelM** [comment]
Probably... I'll leave it be for now.
