### ISSUE TITLE
No Icon is placed for archaeological_site area

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#68]
related to this issues:
https://github.com/IsraelHikingMap/Site/issues/181
In Massada the site is an area and not a POI.

**Comment by zstadler** [comment]
Icons are placed on nodes, not on areas, because of the concern in duplication, as exists in names of cities.

I re-examined the concern by analyzing the current mapping in Israel. Out of 80 archaeological_site areas in Israel, only 5 have overlapping archaeological_site nodes. 3 of them have a single POI - duplicating the tags of the area - which seems like [a mapping error](http://wiki.openstreetmap.org/wiki/Tag:historic%3Darchaeological_site#Mapping): "An archeological site is mapped as a node or an area with historic=archaeological_site".

There are 2 complex archaeological sites, Tel Megiddo and Tel Gezer, that have multiple overlapping nodes. Most of them are annotating specific locations within the site. I've posted a [question on the OSM forum](http://forum.openstreetmap.org/viewtopic.php?pid=598383) about the appropriate tagging of such locations.
