### ISSUE TITLE
IHM: nature reserve border and green trails issue

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Map#72]
See the following link:
http://israelhiking.osm.org.il/#/17/31.7551/35.0250
It shows a green trail next to the border of a natural reserve, you can't really understand which is which.
http://israelhiking.osm.org.il/#/17/31.5340/34.8893
This one too, I thought the green trail doesn't really exists and that it is the border of the nature reserve...

Maybe we need to change it to a green halo instead of this complicated border, what do you think?

**Comment by zstadler** [comment]
Changing to a green halo is an interesting idea. I'll check it out.

Nevertheless...

The first example does not have a green trail. The "_ . . _ . . _" line is a boundary of another nature reserve that does not have an inner annotation. This happens when a single area of a multi-polygon is made of more than one way. I could not find a feasible solution to this exception.

The trail in the second example is made of two lines with same pattern and pitch. A Nature reserve border is made of 3 closer lines, each with different pattern, width and/or pitch.

Overall, the map has many cases of similar, yet different symbols, to represent different entities. For example:
- footway vs. path vs. cycleway
- different grade levels for tracks
- forest vs. farmland areas

As long as we think these differences are important, the map reader needs to be aware of the nuances.

**Comment by HarelM** [comment]
True but the green color along the lines is confusing more than other features - this is the only border I think that is represented by lines while other borders are area filled.
In any case, since I found it confusing, and I'm very familiar with our marking it might be confusing to others as well.

**Comment by zstadler** [comment]
As I said, I'll check it out.

However,
All important area fills have line borders: residential, military, lakes, Area A, and Area B. 
Areas that do not have a line border are the areas were the border is not that important, such as sand, forest, farmland, etc.
Nature reserves are the only area that does not have a fill, for obvious reasons.

**Comment by HarelM** [comment]
Looks great!
Please update the legend image in the site project.

**Comment by zstadler** [comment]
This will be done with #36 or with the next significant change in the style.
