### ISSUE TITLE
MTB IL: elevation contours invisible

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/Map#73]
The contours are too dim and thin to be seen on a smartphone while riding. Use the ones used in IHM.

**Comment by zstadler** [comment]
For example, [here](http://israelhiking.osm.org.il/#/15/30.3751/34.8546)

MTB IL tile | IHM tile
:----:|:----:
![mtbil13479](https://cloud.githubusercontent.com/assets/1304610/16779670/e96697b2-487b-11e6-9186-8dac7e80aa04.png)|![ihm13479](https://cloud.githubusercontent.com/assets/1304610/16779682/f22f056e-487b-11e6-9d34-d50c7bcd2e2c.png)

It looks like the MTB Contours need to be less dim and larger than the IHM contours in order to be seen above the darker background.

**Comment by valleyofdawn** [comment]
So will you use it?

**Comment by zstadler** [comment]
It can be your first contribution - change the line width for contours in the MTB rules ;-)

**Comment by valleyofdawn** [comment]
Will get there eventually
