### ISSUE TITLE
Black, blue, green and red routes of Ein Sha'al doesn't appear on map

### ISSUE THREAD

**Issue by eyaldar** [IsraelHikingMap/Map#90]
Hi, on last Saturday I traveled at Sha'al stream near road 89 and noticed most of the routes doesn't appear on the map. 

This is a description of the route in hebrew including a map:
http://wap.mapa.co.il/smartapp/mapasite/gateitem.aspx?recordid=103376

And in english (no map):
http://www.ozrothagalil.org.il/sitesAndTripEn/23/4/travel-route-ein-shaal-and-the-obscure-stream-out-and-back

**Comment by zstadler** [comment]
Thank you for your report.

The Israel Hiking and Biking Maps show the data from the OpenStreetMap
project. If a trail was not added to OpenStreetMap, it would not show on
the maps. The map is still missing many marked trails, especially foot
trails.

A trails is usually added by recording the GPS trace while walking or
traveling it and using one of the OpenStreetMap editors to update the map
data.

Copying from other maps, such as the links you've attached, is forbidden.

More information on editing the map can be seen in the videos of the the
facebook group
https://www.facebook.com/groups/994960670559126/photos/?filter=videos
or their YouTube version
https://www.youtube.com/watch?v=PUMTUC7i1XU&list=PL8pYDecWd7EjQIyJpPAwSH3UbeZzzQpNo

If you have a GPS trace of the trail, I ill be happy to help you add it to
the map. If you prefer, I can add it myself based on the recording.

GitHub issues in this repository are about improving how the map looks,
which elements to show (or not), and how.

Thanks,
Zeev

**Comment by HarelM** [comment]
Looks like the area you referenced has a lot of missing trails. If you or someone you know can record those trails and add them to the OSM database it would be great!
If you have any questions I think the facebook group would be a great place to start.
We welcome anyone who wants to improve the map.
As Zeev said the issues here are more map appearance oriented but we would very much like to encourage you to be a part of the OSM community by contributing and enjoying everyone's work!

**Comment by valleyofdawn** [comment]
Even if you don't have GPS recordings, if you remember the colors clearly
and see the trails on the bing sat map, you can legally map trace them to
OSM.
Guy

בתאריך 29 באוג׳ 2016 05:19 PM,‏ "Harel M" <notifications@github.com> כתב:

Looks like the area you referenced has a lot of missing trails. If you or
someone you know can record those trails and add them to the OSM database
it would be great!
If you have any questions I think the facebook group would be a great place
to start.
We welcome anyone who wants to improve the map.
As Zeev said the issues here are more map appearance oriented but we would
very much like to encourage you to be a part of the OSM community by
contributing and enjoying everyone's work!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/IsraelHikingMap/Map/issues/90#issuecomment-243137589>,
or mute the thread

**Comment by eyaldar** [comment]
A bit shame I didn't know beforehand, but I'll make sure to record my
trails next time I encounter a missing trail.
Thank you for this great project!
