### ISSUE TITLE
Switch from Maperitive to Vector format

### ISSUE THREAD

**Issue by ATGardner** [IsraelHikingMap/Map#93]
I know it's a big change, and I don't expect anyone to just "do it".
I'm going to have a look at trying to convert the current rules to their RenderTheme format, hopefully I will be able to get to a similar output.
If and when the RenderTheme rules appear satisfactory, I think the entire IsraelHikingMap can be distributed in vector format easily, and in a more flexible container (easily turn on/off different layers, have text layers for different languages, etc.)

However, it does work much slower (at least on my device), so I will also look into using some desktop Java app using the MapForge library (Or should I use Vtm? I am not sure what is the difference between them), and the converted rules, to render raster map tiles (and basically do exactly what Maperitive does - OSM+DEM data+rules => MBTiles sqlite file of raster tiles). This might take some time, as I am not sure such a desktop Java app exist, so maybe I will have to try and develop it myself (any help would be appreciated).

If anyone has any suggestions/tips/ideas, I'd love to hear them.

P.S. - I'm off tomorrow on a two week vacation, so I apologize if I suddenly disappear. I promise to get back and on it when I'm home.

**Comment by HarelM** [comment]
I'm not familiar with MapForge but I would advise to have a look around and see what can be the alternatives in terms of vector format.
I know MapBox is an alternative which looks promising, but I didn't have the time to play around with it enough.
I think you should present a few options and describe which you think is the best before jumping to execution, but hey, since you are the one that's implementing it you are free to do as you please :-)

**Comment by zstadler** [comment]
There are some basic requirements that a vector solution must be able to provide, and I have not figured-out how to address them Mapsforge or Mapbox:

1. Rendering of relations: 
  - Routes for National and regional hiking trails as well as MTB trails
  - Multi-polygons for Nature Reserves/National Parks, forests/woods
2. Rendering control by area size, such as hiding labels by zoom level for small Nature Reserves/National Parks, forests/woods
3. Rendering control by way length, such as hiding road shields by zoom level.
4. Accepting external DEM data. We believe we have a very good 1 arc-sec DEM data for Israel.

**Comment by ATGardner** [comment]
I will look into those requirements when I dig into the RenderTheme. I quite sure rendering by zoom level can be done with it. It also renders the INT as a continuous relation. I think it is quite powerful.
I will check if I can use your ASTER DEM data. And also how I can add the hill shading (which I don't think it supports). I'm sure there will many hurdles along the way.

Regarding MapBox - I'll take a closer look at it. But I don't think it is as powerful as RenderTheme. Maybe I'm wrong.

**Comment by HarelM** [comment]
While I agree with the requirements above, I can't help but wonder if some or all of the requirement above can be translated to OSM data - meaning we download the OSM file, manipulate it with the above requirements somehow and make it available from our server - this way the relevant application can use that file and the render rules we provide to overcome the limitations if they exists...?

**Comment by zstadler** [comment]
@ATGardner you are right. I didn't say zoom was an issue. Area and length could be.

Mappsforge's [RenderTheme rules](https://github.com/mapsforge/mapsforge/blob/master/docs/Rendertheme.md#rules) 
- Refer to ways and nodes only
- Refer only to OSM tags

Mapsforge issue [Add support of other relation types than multipolygon #245](mapsforge/mapsforge#245) suggests that Mapsforge supports multipolygons.

Moreover, [Mapsforge Map-Writer](mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md) can be used to create ways out of multi-polygons. It can do [tag transformations](mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#defining-a-custom-tag-mapping-via-xml), but it does not seem to be able to calculate length, width, or area.

**Comment by HarelM** [comment]
@ATGardner any updates on this? did you make any progress?

**Comment by ATGardner** [comment]
I haven't checked it out yet, no.
I was trying to find a simple desktop solution that uses a MapForge theme file to just render a map, and didn't get far. I was able to render a map of Berlin (A file I downloaded in advance, not directly from any server), and it was clunky and buggy.
I do have the OpenAndroMaps file of Israel on my BCNav, and I think it renders quite nice. The lack of hill shading is annoying. Where is that "hole" example you posted?

**Comment by zstadler** [comment]
Stumbled upon [maputnik](https:/maputnik/editor) - a visual style editor for Mapbox GL

**Comment by HarelM** [comment]
Seems like things are more mature nowadays.
I found this project which lists a lot of other projects (including mapuntik):
https://github.com/mapbox/awesome-vector-tiles
The main question I have regarding vector tiles is if we can provide a service that returns a png image given a vector tile (and our json style), this way we can support current format while evolving to a more up-to-date technology.
The question is how much time does it take to generate vector tiles from an OSM pbf file and how much time does it take to update them. I hope the answer will be that it's much faster than today, because without the png images we relay on client code to render the tiles which will cause it to be less accessible for all current clients (assuming some of them do not support tile vectors).

**Comment by zstadler** [comment]
Interesting approach of using docker described at [](https://blog.klokantech.com/2018/04/maps-with-docker.html)

**Comment by HarelM** [comment]
Very interesting!
Using mapnik through node npm, cool!
https://github.com/openmaptiles/generate-vectortiles/blob/master/Dockerfile

**Comment by HarelM** [comment]
Docker on windows can also run linux containers if you set it to run them, so we might be able to use this solution as is (In theory).

**Comment by HarelM** [comment]
An interesting article about rendering rules:
https://boundlessgeo.com/2017/01/using-mapbox-style-objects-open-layers/
Those are the maintainers of the following library which can be used with openlayers to render the map on the client side and not the server side.
https://github.com/boundlessgeo/ol-mapbox-style
I don't know what are the required tools in order to edit/create this mapbox GL style file though...

**Comment by zstadler** [comment]
[OpenMapTiles](https://openmaptiles.org/docs/) claims to be _Open-source maps made for self-hosting_

Its capabilities include Vector and Raster tiles, server running on Docker, compatibility with Leaflet, OpenLayers, and MapBox SDKs for Android and iOS.

The source code is [available on Github](https://github.com/openmaptiles)

**Comment by zstadler** [comment]
#### POC tasks
- [x] Install a vector tile server
- [ ] Enable a style editor, like [Maputnik](https://maputnik.github.io/) on it
- [ ] Extend the schema for missing tags, such as `colour` and `mtb:*`
- [ ] Create IHM style
- [ ] Create IMTB style
- [ ] Add contour vector tiles
- [ ] Add Hillshades raster tiles

#### Production tasks
- [ ] Daily updates based on Geofabrik
- [ ] Continuous updates based on openstreetmap.fr
- [ ] Continuous updates directly from OSM

**Comment by dobihp** [comment]
Please note that Mapbox Inc. has filed a lawsuit against  Klokan Technologies GmbH for copyright infringement on Open Map Tiles.

**Comment by zstadler** [comment]
Can you provide some references?
What portions are claimed to be infringing?

**Comment by zstadler** [comment]
#### Missing tags (WIP)
- [ ] highway
  - [ ] colour
- [ ] water, waterway
  - [ ] intermittent
- [ ] route relations
  - [ ] network
  - [ ] operator
  - [ ] mtb:scale

**Comment by zstadler** [comment]
@dobihp wrote:
> Please note that Mapbox Inc. has filed a lawsuit against Klokan Technologies GmbH for copyright infringement on Open Map Tiles.

with no additional details. 

My understanding from [this issue and post](https://github.com/osm2vectortiles/osm2vectortiles/issues/387#issuecomment-273492760) is that the General Counsel of MapBox made claims (not a lawsuit) against the OSM2VectorTiles project. After a long  online and offline discussion, the OpenMapTiles project was created in order to avoid these claims. 

Similar claims have not been made on the OpenMapTiles issue list.

Searching the web for a lawsuit involving Mapbox and either OpenMapTiles or Klokan Technologies found nothing relevant. 

Without information to the contrary, no further action seems to be required on the legal aspect.

**Comment by HarelM** [comment]
As part of looking into some offline solutions I've looked at geopackage in the past.
When I wanted to see if there's a conversion from geopackage styling to openlayers I found this SO question:
https://stackoverflow.com/questions/35830350/how-to-style-layers-with-sld-in-ol3
Which led me to this project:
https://github.com/Norkart/SLDexit
Maybe we can use an existing SLD and convert it to mapbox style.

**Comment by zstadler** [comment]
Done
